from .employees.employee_list import employee_list
from .trainings.trainings_list import trainings_list
from .trainings.form import training_form
from .home import home
from .auth.logout import logout_user
from .employees.form import employee_form
from .departments.department_list import department_list
from .departments.department_form import department_form
from .departments.department_details import department_details
